export const LOADING_STATUS = 'LOADING_STATUS';

export const FETCH_COURSE_LIST_REQUEST = 'REQUEST_COURSE_LIST_REQUEST';
export const FETCH_COURSE_LIST_SUCCESS = 'FETCH_COURSE_LIST_SUCCESS';

//export const FETCH_COURSE_SUCCESS = 'FETCH_COURSE_SUCCESS'; 

export const FETCH_COURSE_LIST = {
    REQUEST: 'FETCH_COURSE_LIST_REQUEST',
    SUCCESS: 'FETCH_COURSE_LIST_SUCCESS',
    FAILURE: 'FETCH_COURSE_LIST_FAILURE'
};

export const FETCH_COURSE = {
    REQUEST: 'FETCH_COURSE_REQUSET',
    SUCCESS: 'FETCH_COURSE_SUCCESS',
    FAILURE: 'FETCH_COURSE_FAILURE'
};

export const SEARCH_COURSE = {
    REQUEST: 'SEARCH_COURSE_REQUEST',
    SUCCESS: 'SEARCH_COURSE_SUCCESS',
    FAILURE: 'SEARCH_COURSE_FAILURE'
};
export const TOGGLE_SIDE_BAR = 'TOGGLE_SIDE_BAR';
